## Version 1.0

FROM centos:7

# usar los parametros para que no realice preguntas. Ver en cada caso que parametris usar.
# Aca en la instalacion usamos el -y para pasar un yes a todo.
RUN yum -y install httpd

# -DFOREGROUD es para dejar corriendo en background el apache.
CMD apachectl -DFOREGROUND
